from __future__ import annotations

from phase0.research.admission.gate import (
    overfit_blocks_admission as _overfit_blocks_admission,
    resolve_admission_gate as _resolve_admission_gate,
    resolve_diagnostic_suites as _resolve_diagnostic_suites,
)
from phase0.research.admission.reports import (
    _format_benchmark_float,
    _format_count_map,
    _format_status_float,
    _format_status_int,
    _load_quality_factor_evidence,
    _md_table,
    _quality_factor_evidence_label,
    _quality_failure_attribution,
    _safe_float,
    _safe_int,
    _safe_str,
    _value_counts,
    admission_command_hint as _admission_command_hint,
    config_command_arg as _config_command_arg,
    required_artifact_names as _required_artifact_names,
    write_governance_report as _write_governance_report,
    write_report as _write_report,
)
from phase0.research.admission.review import (
    admission_action as _admission_action,
    attach_price_adjustment_status as _attach_price_adjustment_status,
    build_constraint_review as _build_constraint_review,
    build_window_matrix as _build_window_matrix,
    factor_missing_window_count as _factor_missing_window_count,
    industry_concentration_window_count as _industry_concentration_window_count,
    industry_missing_window_count as _industry_missing_window_count,
    numeric_column as _numeric_column,
    parameter_unstable_window_count as _parameter_unstable_window_count,
    price_adjustment_fail_window_count as _price_adjustment_fail_window_count,
    turnover_fail_window_count as _turnover_fail_window_count,
    window_metrics as _window_metrics,
)
from phase0.research.admission.runner import StrategyAdmissionResult, run_strategy_admission
from phase0.research.admission.strategy_scope import (
    _force_strategy_set_enabled_for_admission,
    _resolve_strategy_scope,
)

__all__ = [
    "StrategyAdmissionResult",
    "run_strategy_admission",
    "_admission_action",
    "_admission_command_hint",
    "_attach_price_adjustment_status",
    "_build_constraint_review",
    "_build_window_matrix",
    "_config_command_arg",
    "_factor_missing_window_count",
    "_force_strategy_set_enabled_for_admission",
    "_format_benchmark_float",
    "_format_count_map",
    "_format_status_float",
    "_format_status_int",
    "_industry_concentration_window_count",
    "_industry_missing_window_count",
    "_load_quality_factor_evidence",
    "_md_table",
    "_numeric_column",
    "_overfit_blocks_admission",
    "_parameter_unstable_window_count",
    "_price_adjustment_fail_window_count",
    "_quality_factor_evidence_label",
    "_quality_failure_attribution",
    "_required_artifact_names",
    "_resolve_admission_gate",
    "_resolve_diagnostic_suites",
    "_resolve_strategy_scope",
    "_safe_float",
    "_safe_int",
    "_safe_str",
    "_turnover_fail_window_count",
    "_value_counts",
    "_window_metrics",
    "_write_governance_report",
    "_write_report",
]
